# Generated by Django 4.1.3 on 2022-12-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('created_by', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
